# 异常 try except 相当于java try catch

try:
    i = 1 / 0
except BaseException:
    print("there an exception")
